trigger:
- main

pool:
  vmImage: ubuntu-latest

- task: RunARMTTKTests@1
  inputs:
    templatelocation: '$(System.DefaultWorkingDirectory)\infra'
    resultLocation: '$(System.DefaultWorkingDirectory)\results'
    skipTests: 
    mainTemplates: 
    allTemplatesMain: true
    cliOutputResults: true

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '$(System.DefaultWorkingDirectory)\results\*-armttk.xml'
  condition: always()
